spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.114.129:8080/itoken/itoken-config.git
          search-paths: respo
          username: xiaoqiisnotxiaoqi
          password: Q+j=b1234


server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.114.131:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info